apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb-deployment
  namespace: lanflo-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: chromadb-volume-claim
      containers:
        - name: chromadb
          image: chromadb/chroma
          volumeMounts:
            - name: app-storage
              mountPath: /data
