apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./chromadb/namespace.yaml
  - ./chromadb/deployment.yaml
  - ./chromadb/service.yaml
  - ./chromadb/volume-claim.yaml
  - ./chromadb/volume.yaml
